### PR TITLE
Add packages of HigherHomologicalAlgebra to the list of Cap project based

### PR DESCRIPTION
**Pull request by kamalsaleh**
packages.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I am not sure. I assume that these lists are autogenerated by PackageJanitor, so merging your PR could cause future conflicts. Please discuss this with @zickgraf.

**Comment by kamalsaleh** [comment]
Exactly, the lists are generated with `PackageJanitor` by extending the site.yml: https://github.com/homalg-project/PackageJanitor/pull/62.

**Comment by kamalsaleh** [comment]
The force-push was to put `QPA2` before `QuotientCategories`.

**Comment by zickgraf** [comment]
@kamalsaleh This PR looks obsolete with 7545094b11c56b3c1e86006a9afc72a6db2059e3 and 08874fc9b92092e393f066a3127ae0a5ec06c7eb. Is this correct?

**Comment by kamalsaleh** [comment]
It is indeed obsolete. Thank you for pointing that out.

**Pull request closed without merging**
